version: "3.8"
services:
  express-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - neo4j
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DBNAME: ${DBNAME}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: postgres
      DBPORT: 5432
      BASE_URL: ${BASE_URL}
      NEO4JURL: ${NEO4JURLBOLT}
      NEO4JUSER: ${NEO4JUSER}
      NEO4JPASSWORD: ${NEO4JPASSWORD}
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DBNAME}
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: ${NEO4JUSER}/${NEO4JPASSWORD}
    ports:
      - "7688:7687"
      - "7475:7474"