openapi: 3.0.0
info:
  title: Test API
  description: Api description
  version: 1.1.0
servers:
  - url: http://localhost:4000/api
    description: Local server
  - url: https://staging-api.example.com
    description: Staging server
security:
  - bearerAuth: [ ]
paths:
  /user/sign-up:
    post:
      summary: User registration
      tags:
        - UserResolver.ts
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              title: A Slack message
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
              required:
                - name
                - username
                - password
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authorization token
  schemas:
    Message:
      title: A Slack message
      type: object
      properties:
        text:
          type: string
      required:
        - text
